/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AdaptiveAMM {
  export type PoolStruct = {
    assetToken: AddressLike;
    quoteToken: AddressLike;
    lpToken: AddressLike;
    assetReserve: BigNumberish;
    quoteReserve: BigNumberish;
    appraisalValue: BigNumberish;
    pegPrice: BigNumberish;
    amplification: BigNumberish;
    lastUpdateTime: BigNumberish;
    tradingFee: BigNumberish;
    isActive: boolean;
  };

  export type PoolStructOutput = [
    assetToken: string,
    quoteToken: string,
    lpToken: string,
    assetReserve: bigint,
    quoteReserve: bigint,
    appraisalValue: bigint,
    pegPrice: bigint,
    amplification: bigint,
    lastUpdateTime: bigint,
    tradingFee: bigint,
    isActive: boolean
  ] & {
    assetToken: string;
    quoteToken: string;
    lpToken: string;
    assetReserve: bigint;
    quoteReserve: bigint;
    appraisalValue: bigint;
    pegPrice: bigint;
    amplification: bigint;
    lastUpdateTime: bigint;
    tradingFee: bigint;
    isActive: boolean;
  };
}

export interface AdaptiveAMMInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASIS_POINTS"
      | "MIN_LIQUIDITY"
      | "N"
      | "PRECISION"
      | "addLiquidity"
      | "complianceEnabled"
      | "complianceRegistry"
      | "createPool"
      | "getAmountOut"
      | "getCurrentPrice"
      | "getLPBalance"
      | "getLPToken"
      | "getLPTotalSupply"
      | "getPool"
      | "getPoolCount"
      | "getPoolId"
      | "owner"
      | "poolIds"
      | "pools"
      | "removeLiquidity"
      | "renounceOwnership"
      | "setComplianceRegistry"
      | "swap"
      | "toggleCompliance"
      | "transferOwnership"
      | "updateAmplification"
      | "updateAppraisal"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AmplificationUpdated"
      | "AppraisalUpdated"
      | "ComplianceRegistrySet"
      | "ComplianceToggled"
      | "LiquidityAdded"
      | "LiquidityRemoved"
      | "OwnershipTransferred"
      | "PoolCreated"
      | "Swap"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_LIQUIDITY",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "N", values?: undefined): string;
  encodeFunctionData(functionFragment: "PRECISION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "addLiquidity",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "complianceEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "complianceRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createPool",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAmountOut",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentPrice",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLPBalance",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLPToken",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLPTotalSupply",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getPool", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getPoolCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "poolIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pools", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "removeLiquidity",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setComplianceRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swap",
    values: [BytesLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "toggleCompliance",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAmplification",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAppraisal",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_LIQUIDITY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "N", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "PRECISION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "complianceEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "complianceRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAmountOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLPBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLPToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLPTotalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPoolCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPoolId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "poolIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pools", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setComplianceRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "toggleCompliance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAmplification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAppraisal",
    data: BytesLike
  ): Result;
}

export namespace AmplificationUpdatedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    oldA: BigNumberish,
    newA: BigNumberish
  ];
  export type OutputTuple = [poolId: string, oldA: bigint, newA: bigint];
  export interface OutputObject {
    poolId: string;
    oldA: bigint;
    newA: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AppraisalUpdatedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    oldValue: BigNumberish,
    newValue: BigNumberish,
    newPegPrice: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    oldValue: bigint,
    newValue: bigint,
    newPegPrice: bigint
  ];
  export interface OutputObject {
    poolId: string;
    oldValue: bigint;
    newValue: bigint;
    newPegPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplianceRegistrySetEvent {
  export type InputTuple = [registry: AddressLike];
  export type OutputTuple = [registry: string];
  export interface OutputObject {
    registry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplianceToggledEvent {
  export type InputTuple = [enabled: boolean];
  export type OutputTuple = [enabled: boolean];
  export interface OutputObject {
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityAddedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    provider: AddressLike,
    assetAmount: BigNumberish,
    quoteAmount: BigNumberish,
    lpTokens: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    provider: string,
    assetAmount: bigint,
    quoteAmount: bigint,
    lpTokens: bigint
  ];
  export interface OutputObject {
    poolId: string;
    provider: string;
    assetAmount: bigint;
    quoteAmount: bigint;
    lpTokens: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityRemovedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    provider: AddressLike,
    assetAmount: BigNumberish,
    quoteAmount: BigNumberish,
    lpTokens: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    provider: string,
    assetAmount: bigint,
    quoteAmount: bigint,
    lpTokens: bigint
  ];
  export interface OutputObject {
    poolId: string;
    provider: string;
    assetAmount: bigint;
    quoteAmount: bigint;
    lpTokens: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolCreatedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    assetToken: AddressLike,
    quoteToken: AddressLike,
    lpToken: AddressLike,
    initialAssetAmount: BigNumberish,
    initialQuoteAmount: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    assetToken: string,
    quoteToken: string,
    lpToken: string,
    initialAssetAmount: bigint,
    initialQuoteAmount: bigint
  ];
  export interface OutputObject {
    poolId: string;
    assetToken: string;
    quoteToken: string;
    lpToken: string;
    initialAssetAmount: bigint;
    initialQuoteAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapEvent {
  export type InputTuple = [
    poolId: BytesLike,
    trader: AddressLike,
    tokenIn: AddressLike,
    tokenOut: AddressLike,
    amountIn: BigNumberish,
    amountOut: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    trader: string,
    tokenIn: string,
    tokenOut: string,
    amountIn: bigint,
    amountOut: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    poolId: string;
    trader: string;
    tokenIn: string;
    tokenOut: string;
    amountIn: bigint;
    amountOut: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AdaptiveAMM extends BaseContract {
  connect(runner?: ContractRunner | null): AdaptiveAMM;
  waitForDeployment(): Promise<this>;

  interface: AdaptiveAMMInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASIS_POINTS: TypedContractMethod<[], [bigint], "view">;

  MIN_LIQUIDITY: TypedContractMethod<[], [bigint], "view">;

  N: TypedContractMethod<[], [bigint], "view">;

  PRECISION: TypedContractMethod<[], [bigint], "view">;

  addLiquidity: TypedContractMethod<
    [poolId: BytesLike, assetAmount: BigNumberish, quoteAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  complianceEnabled: TypedContractMethod<[], [boolean], "view">;

  complianceRegistry: TypedContractMethod<[], [string], "view">;

  createPool: TypedContractMethod<
    [
      assetToken: AddressLike,
      quoteToken: AddressLike,
      initialAsset: BigNumberish,
      initialQuote: BigNumberish,
      appraisalValue: BigNumberish,
      tradingFee: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  getAmountOut: TypedContractMethod<
    [poolId: BytesLike, tokenIn: AddressLike, amountIn: BigNumberish],
    [bigint],
    "view"
  >;

  getCurrentPrice: TypedContractMethod<[poolId: BytesLike], [bigint], "view">;

  getLPBalance: TypedContractMethod<
    [poolId: BytesLike, user: AddressLike],
    [bigint],
    "view"
  >;

  getLPToken: TypedContractMethod<[poolId: BytesLike], [string], "view">;

  getLPTotalSupply: TypedContractMethod<[poolId: BytesLike], [bigint], "view">;

  getPool: TypedContractMethod<
    [poolId: BytesLike],
    [AdaptiveAMM.PoolStructOutput],
    "view"
  >;

  getPoolCount: TypedContractMethod<[], [bigint], "view">;

  getPoolId: TypedContractMethod<[index: BigNumberish], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  poolIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  pools: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        assetToken: string;
        quoteToken: string;
        lpToken: string;
        assetReserve: bigint;
        quoteReserve: bigint;
        appraisalValue: bigint;
        pegPrice: bigint;
        amplification: bigint;
        lastUpdateTime: bigint;
        tradingFee: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  removeLiquidity: TypedContractMethod<
    [poolId: BytesLike, lpTokens: BigNumberish],
    [[bigint, bigint] & { assetAmount: bigint; quoteAmount: bigint }],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setComplianceRegistry: TypedContractMethod<
    [_registry: AddressLike],
    [void],
    "nonpayable"
  >;

  swap: TypedContractMethod<
    [
      poolId: BytesLike,
      tokenIn: AddressLike,
      amountIn: BigNumberish,
      minAmountOut: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  toggleCompliance: TypedContractMethod<
    [_enabled: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateAmplification: TypedContractMethod<
    [poolId: BytesLike, newA: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateAppraisal: TypedContractMethod<
    [poolId: BytesLike, newAppraisal: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASIS_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_LIQUIDITY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "N"): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRECISION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addLiquidity"
  ): TypedContractMethod<
    [poolId: BytesLike, assetAmount: BigNumberish, quoteAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "complianceEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "complianceRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createPool"
  ): TypedContractMethod<
    [
      assetToken: AddressLike,
      quoteToken: AddressLike,
      initialAsset: BigNumberish,
      initialQuote: BigNumberish,
      appraisalValue: BigNumberish,
      tradingFee: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAmountOut"
  ): TypedContractMethod<
    [poolId: BytesLike, tokenIn: AddressLike, amountIn: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentPrice"
  ): TypedContractMethod<[poolId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLPBalance"
  ): TypedContractMethod<
    [poolId: BytesLike, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLPToken"
  ): TypedContractMethod<[poolId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getLPTotalSupply"
  ): TypedContractMethod<[poolId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPool"
  ): TypedContractMethod<
    [poolId: BytesLike],
    [AdaptiveAMM.PoolStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPoolCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPoolId"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "poolIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "pools"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        assetToken: string;
        quoteToken: string;
        lpToken: string;
        assetReserve: bigint;
        quoteReserve: bigint;
        appraisalValue: bigint;
        pegPrice: bigint;
        amplification: bigint;
        lastUpdateTime: bigint;
        tradingFee: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "removeLiquidity"
  ): TypedContractMethod<
    [poolId: BytesLike, lpTokens: BigNumberish],
    [[bigint, bigint] & { assetAmount: bigint; quoteAmount: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setComplianceRegistry"
  ): TypedContractMethod<[_registry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "swap"
  ): TypedContractMethod<
    [
      poolId: BytesLike,
      tokenIn: AddressLike,
      amountIn: BigNumberish,
      minAmountOut: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "toggleCompliance"
  ): TypedContractMethod<[_enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateAmplification"
  ): TypedContractMethod<
    [poolId: BytesLike, newA: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateAppraisal"
  ): TypedContractMethod<
    [poolId: BytesLike, newAppraisal: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AmplificationUpdated"
  ): TypedContractEvent<
    AmplificationUpdatedEvent.InputTuple,
    AmplificationUpdatedEvent.OutputTuple,
    AmplificationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AppraisalUpdated"
  ): TypedContractEvent<
    AppraisalUpdatedEvent.InputTuple,
    AppraisalUpdatedEvent.OutputTuple,
    AppraisalUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ComplianceRegistrySet"
  ): TypedContractEvent<
    ComplianceRegistrySetEvent.InputTuple,
    ComplianceRegistrySetEvent.OutputTuple,
    ComplianceRegistrySetEvent.OutputObject
  >;
  getEvent(
    key: "ComplianceToggled"
  ): TypedContractEvent<
    ComplianceToggledEvent.InputTuple,
    ComplianceToggledEvent.OutputTuple,
    ComplianceToggledEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityAdded"
  ): TypedContractEvent<
    LiquidityAddedEvent.InputTuple,
    LiquidityAddedEvent.OutputTuple,
    LiquidityAddedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityRemoved"
  ): TypedContractEvent<
    LiquidityRemovedEvent.InputTuple,
    LiquidityRemovedEvent.OutputTuple,
    LiquidityRemovedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PoolCreated"
  ): TypedContractEvent<
    PoolCreatedEvent.InputTuple,
    PoolCreatedEvent.OutputTuple,
    PoolCreatedEvent.OutputObject
  >;
  getEvent(
    key: "Swap"
  ): TypedContractEvent<
    SwapEvent.InputTuple,
    SwapEvent.OutputTuple,
    SwapEvent.OutputObject
  >;

  filters: {
    "AmplificationUpdated(bytes32,uint256,uint256)": TypedContractEvent<
      AmplificationUpdatedEvent.InputTuple,
      AmplificationUpdatedEvent.OutputTuple,
      AmplificationUpdatedEvent.OutputObject
    >;
    AmplificationUpdated: TypedContractEvent<
      AmplificationUpdatedEvent.InputTuple,
      AmplificationUpdatedEvent.OutputTuple,
      AmplificationUpdatedEvent.OutputObject
    >;

    "AppraisalUpdated(bytes32,uint256,uint256,uint256)": TypedContractEvent<
      AppraisalUpdatedEvent.InputTuple,
      AppraisalUpdatedEvent.OutputTuple,
      AppraisalUpdatedEvent.OutputObject
    >;
    AppraisalUpdated: TypedContractEvent<
      AppraisalUpdatedEvent.InputTuple,
      AppraisalUpdatedEvent.OutputTuple,
      AppraisalUpdatedEvent.OutputObject
    >;

    "ComplianceRegistrySet(address)": TypedContractEvent<
      ComplianceRegistrySetEvent.InputTuple,
      ComplianceRegistrySetEvent.OutputTuple,
      ComplianceRegistrySetEvent.OutputObject
    >;
    ComplianceRegistrySet: TypedContractEvent<
      ComplianceRegistrySetEvent.InputTuple,
      ComplianceRegistrySetEvent.OutputTuple,
      ComplianceRegistrySetEvent.OutputObject
    >;

    "ComplianceToggled(bool)": TypedContractEvent<
      ComplianceToggledEvent.InputTuple,
      ComplianceToggledEvent.OutputTuple,
      ComplianceToggledEvent.OutputObject
    >;
    ComplianceToggled: TypedContractEvent<
      ComplianceToggledEvent.InputTuple,
      ComplianceToggledEvent.OutputTuple,
      ComplianceToggledEvent.OutputObject
    >;

    "LiquidityAdded(bytes32,address,uint256,uint256,uint256)": TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;
    LiquidityAdded: TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;

    "LiquidityRemoved(bytes32,address,uint256,uint256,uint256)": TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;
    LiquidityRemoved: TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PoolCreated(bytes32,address,address,address,uint256,uint256)": TypedContractEvent<
      PoolCreatedEvent.InputTuple,
      PoolCreatedEvent.OutputTuple,
      PoolCreatedEvent.OutputObject
    >;
    PoolCreated: TypedContractEvent<
      PoolCreatedEvent.InputTuple,
      PoolCreatedEvent.OutputTuple,
      PoolCreatedEvent.OutputObject
    >;

    "Swap(bytes32,address,address,address,uint256,uint256,uint256)": TypedContractEvent<
      SwapEvent.InputTuple,
      SwapEvent.OutputTuple,
      SwapEvent.OutputObject
    >;
    Swap: TypedContractEvent<
      SwapEvent.InputTuple,
      SwapEvent.OutputTuple,
      SwapEvent.OutputObject
    >;
  };
}
