/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ATSIdentityRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addComplianceOperator"
      | "blockCountry"
      | "blockedCountries"
      | "complianceOperators"
      | "contains"
      | "demoModeEnabled"
      | "getContractInfo"
      | "getIdentity"
      | "getRegisteredContractCount"
      | "getRegisteredCount"
      | "getRegisteredInvestorCount"
      | "identity"
      | "investorCountry"
      | "isRegisteredContract"
      | "isVerified"
      | "owner"
      | "registerContract"
      | "removeComplianceOperator"
      | "renounceOwnership"
      | "revokeInvestor"
      | "selfRegister"
      | "setDemoMode"
      | "transferOwnership"
      | "unblockCountry"
      | "unregisterContract"
      | "verifyInvestor"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ComplianceOperatorAdded"
      | "ComplianceOperatorRemoved"
      | "ContractRegistered"
      | "ContractUnregistered"
      | "CountryBlocked"
      | "CountryUnblocked"
      | "DemoModeSet"
      | "IdentityRevoked"
      | "IdentityVerified"
      | "OwnershipTransferred"
      | "SelfRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addComplianceOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "blockCountry",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "blockedCountries",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "complianceOperators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "contains",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "demoModeEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContractInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getIdentity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRegisteredContractCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRegisteredCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRegisteredInvestorCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "identity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "investorCountry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegisteredContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerified",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerContract",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeComplianceOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeInvestor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "selfRegister",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDemoMode",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unblockCountry",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unregisterContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyInvestor",
    values: [AddressLike, BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "addComplianceOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blockCountry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blockedCountries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "complianceOperators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "contains", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "demoModeEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegisteredContractCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegisteredCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegisteredInvestorCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "identity", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "investorCountry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegisteredContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isVerified", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeComplianceOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeInvestor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "selfRegister",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDemoMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unblockCountry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unregisterContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyInvestor",
    data: BytesLike
  ): Result;
}

export namespace ComplianceOperatorAddedEvent {
  export type InputTuple = [operator: AddressLike];
  export type OutputTuple = [operator: string];
  export interface OutputObject {
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplianceOperatorRemovedEvent {
  export type InputTuple = [operator: AddressLike];
  export type OutputTuple = [operator: string];
  export interface OutputObject {
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractRegisteredEvent {
  export type InputTuple = [contractAddress: AddressLike, contractType: string];
  export type OutputTuple = [contractAddress: string, contractType: string];
  export interface OutputObject {
    contractAddress: string;
    contractType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractUnregisteredEvent {
  export type InputTuple = [contractAddress: AddressLike];
  export type OutputTuple = [contractAddress: string];
  export interface OutputObject {
    contractAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CountryBlockedEvent {
  export type InputTuple = [country: BigNumberish];
  export type OutputTuple = [country: bigint];
  export interface OutputObject {
    country: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CountryUnblockedEvent {
  export type InputTuple = [country: BigNumberish];
  export type OutputTuple = [country: bigint];
  export interface OutputObject {
    country: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DemoModeSetEvent {
  export type InputTuple = [enabled: boolean];
  export type OutputTuple = [enabled: boolean];
  export interface OutputObject {
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityRevokedEvent {
  export type InputTuple = [investor: AddressLike];
  export type OutputTuple = [investor: string];
  export interface OutputObject {
    investor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityVerifiedEvent {
  export type InputTuple = [
    investor: AddressLike,
    country: BigNumberish,
    tier: string
  ];
  export type OutputTuple = [investor: string, country: bigint, tier: string];
  export interface OutputObject {
    investor: string;
    country: bigint;
    tier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SelfRegisteredEvent {
  export type InputTuple = [investor: AddressLike];
  export type OutputTuple = [investor: string];
  export interface OutputObject {
    investor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ATSIdentityRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ATSIdentityRegistry;
  waitForDeployment(): Promise<this>;

  interface: ATSIdentityRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addComplianceOperator: TypedContractMethod<
    [operator: AddressLike],
    [void],
    "nonpayable"
  >;

  blockCountry: TypedContractMethod<
    [country: BigNumberish],
    [void],
    "nonpayable"
  >;

  blockedCountries: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  complianceOperators: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  contains: TypedContractMethod<[_userAddress: AddressLike], [boolean], "view">;

  demoModeEnabled: TypedContractMethod<[], [boolean], "view">;

  getContractInfo: TypedContractMethod<
    [contractAddress: AddressLike],
    [
      [boolean, string, bigint] & {
        isRegistered: boolean;
        contractType: string;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  getIdentity: TypedContractMethod<
    [investor: AddressLike],
    [
      [boolean, bigint, string, bigint] & {
        isVerifiedStatus: boolean;
        country: bigint;
        tier: string;
        verifiedAt: bigint;
      }
    ],
    "view"
  >;

  getRegisteredContractCount: TypedContractMethod<[], [bigint], "view">;

  getRegisteredCount: TypedContractMethod<[], [bigint], "view">;

  getRegisteredInvestorCount: TypedContractMethod<[], [bigint], "view">;

  identity: TypedContractMethod<[_userAddress: AddressLike], [string], "view">;

  investorCountry: TypedContractMethod<
    [_userAddress: AddressLike],
    [bigint],
    "view"
  >;

  isRegisteredContract: TypedContractMethod<
    [contractAddress: AddressLike],
    [boolean],
    "view"
  >;

  isVerified: TypedContractMethod<
    [_userAddress: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerContract: TypedContractMethod<
    [contractAddress: AddressLike, contractType: string],
    [void],
    "nonpayable"
  >;

  removeComplianceOperator: TypedContractMethod<
    [operator: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeInvestor: TypedContractMethod<
    [investor: AddressLike],
    [void],
    "nonpayable"
  >;

  selfRegister: TypedContractMethod<[], [void], "nonpayable">;

  setDemoMode: TypedContractMethod<[enabled: boolean], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unblockCountry: TypedContractMethod<
    [country: BigNumberish],
    [void],
    "nonpayable"
  >;

  unregisterContract: TypedContractMethod<
    [contractAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyInvestor: TypedContractMethod<
    [investor: AddressLike, country: BigNumberish, tier: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addComplianceOperator"
  ): TypedContractMethod<[operator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "blockCountry"
  ): TypedContractMethod<[country: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "blockedCountries"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "complianceOperators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "contains"
  ): TypedContractMethod<[_userAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "demoModeEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getContractInfo"
  ): TypedContractMethod<
    [contractAddress: AddressLike],
    [
      [boolean, string, bigint] & {
        isRegistered: boolean;
        contractType: string;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getIdentity"
  ): TypedContractMethod<
    [investor: AddressLike],
    [
      [boolean, bigint, string, bigint] & {
        isVerifiedStatus: boolean;
        country: bigint;
        tier: string;
        verifiedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRegisteredContractCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRegisteredCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRegisteredInvestorCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "identity"
  ): TypedContractMethod<[_userAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "investorCountry"
  ): TypedContractMethod<[_userAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isRegisteredContract"
  ): TypedContractMethod<[contractAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isVerified"
  ): TypedContractMethod<[_userAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerContract"
  ): TypedContractMethod<
    [contractAddress: AddressLike, contractType: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeComplianceOperator"
  ): TypedContractMethod<[operator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeInvestor"
  ): TypedContractMethod<[investor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "selfRegister"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDemoMode"
  ): TypedContractMethod<[enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unblockCountry"
  ): TypedContractMethod<[country: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unregisterContract"
  ): TypedContractMethod<[contractAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyInvestor"
  ): TypedContractMethod<
    [investor: AddressLike, country: BigNumberish, tier: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ComplianceOperatorAdded"
  ): TypedContractEvent<
    ComplianceOperatorAddedEvent.InputTuple,
    ComplianceOperatorAddedEvent.OutputTuple,
    ComplianceOperatorAddedEvent.OutputObject
  >;
  getEvent(
    key: "ComplianceOperatorRemoved"
  ): TypedContractEvent<
    ComplianceOperatorRemovedEvent.InputTuple,
    ComplianceOperatorRemovedEvent.OutputTuple,
    ComplianceOperatorRemovedEvent.OutputObject
  >;
  getEvent(
    key: "ContractRegistered"
  ): TypedContractEvent<
    ContractRegisteredEvent.InputTuple,
    ContractRegisteredEvent.OutputTuple,
    ContractRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ContractUnregistered"
  ): TypedContractEvent<
    ContractUnregisteredEvent.InputTuple,
    ContractUnregisteredEvent.OutputTuple,
    ContractUnregisteredEvent.OutputObject
  >;
  getEvent(
    key: "CountryBlocked"
  ): TypedContractEvent<
    CountryBlockedEvent.InputTuple,
    CountryBlockedEvent.OutputTuple,
    CountryBlockedEvent.OutputObject
  >;
  getEvent(
    key: "CountryUnblocked"
  ): TypedContractEvent<
    CountryUnblockedEvent.InputTuple,
    CountryUnblockedEvent.OutputTuple,
    CountryUnblockedEvent.OutputObject
  >;
  getEvent(
    key: "DemoModeSet"
  ): TypedContractEvent<
    DemoModeSetEvent.InputTuple,
    DemoModeSetEvent.OutputTuple,
    DemoModeSetEvent.OutputObject
  >;
  getEvent(
    key: "IdentityRevoked"
  ): TypedContractEvent<
    IdentityRevokedEvent.InputTuple,
    IdentityRevokedEvent.OutputTuple,
    IdentityRevokedEvent.OutputObject
  >;
  getEvent(
    key: "IdentityVerified"
  ): TypedContractEvent<
    IdentityVerifiedEvent.InputTuple,
    IdentityVerifiedEvent.OutputTuple,
    IdentityVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SelfRegistered"
  ): TypedContractEvent<
    SelfRegisteredEvent.InputTuple,
    SelfRegisteredEvent.OutputTuple,
    SelfRegisteredEvent.OutputObject
  >;

  filters: {
    "ComplianceOperatorAdded(address)": TypedContractEvent<
      ComplianceOperatorAddedEvent.InputTuple,
      ComplianceOperatorAddedEvent.OutputTuple,
      ComplianceOperatorAddedEvent.OutputObject
    >;
    ComplianceOperatorAdded: TypedContractEvent<
      ComplianceOperatorAddedEvent.InputTuple,
      ComplianceOperatorAddedEvent.OutputTuple,
      ComplianceOperatorAddedEvent.OutputObject
    >;

    "ComplianceOperatorRemoved(address)": TypedContractEvent<
      ComplianceOperatorRemovedEvent.InputTuple,
      ComplianceOperatorRemovedEvent.OutputTuple,
      ComplianceOperatorRemovedEvent.OutputObject
    >;
    ComplianceOperatorRemoved: TypedContractEvent<
      ComplianceOperatorRemovedEvent.InputTuple,
      ComplianceOperatorRemovedEvent.OutputTuple,
      ComplianceOperatorRemovedEvent.OutputObject
    >;

    "ContractRegistered(address,string)": TypedContractEvent<
      ContractRegisteredEvent.InputTuple,
      ContractRegisteredEvent.OutputTuple,
      ContractRegisteredEvent.OutputObject
    >;
    ContractRegistered: TypedContractEvent<
      ContractRegisteredEvent.InputTuple,
      ContractRegisteredEvent.OutputTuple,
      ContractRegisteredEvent.OutputObject
    >;

    "ContractUnregistered(address)": TypedContractEvent<
      ContractUnregisteredEvent.InputTuple,
      ContractUnregisteredEvent.OutputTuple,
      ContractUnregisteredEvent.OutputObject
    >;
    ContractUnregistered: TypedContractEvent<
      ContractUnregisteredEvent.InputTuple,
      ContractUnregisteredEvent.OutputTuple,
      ContractUnregisteredEvent.OutputObject
    >;

    "CountryBlocked(uint16)": TypedContractEvent<
      CountryBlockedEvent.InputTuple,
      CountryBlockedEvent.OutputTuple,
      CountryBlockedEvent.OutputObject
    >;
    CountryBlocked: TypedContractEvent<
      CountryBlockedEvent.InputTuple,
      CountryBlockedEvent.OutputTuple,
      CountryBlockedEvent.OutputObject
    >;

    "CountryUnblocked(uint16)": TypedContractEvent<
      CountryUnblockedEvent.InputTuple,
      CountryUnblockedEvent.OutputTuple,
      CountryUnblockedEvent.OutputObject
    >;
    CountryUnblocked: TypedContractEvent<
      CountryUnblockedEvent.InputTuple,
      CountryUnblockedEvent.OutputTuple,
      CountryUnblockedEvent.OutputObject
    >;

    "DemoModeSet(bool)": TypedContractEvent<
      DemoModeSetEvent.InputTuple,
      DemoModeSetEvent.OutputTuple,
      DemoModeSetEvent.OutputObject
    >;
    DemoModeSet: TypedContractEvent<
      DemoModeSetEvent.InputTuple,
      DemoModeSetEvent.OutputTuple,
      DemoModeSetEvent.OutputObject
    >;

    "IdentityRevoked(address)": TypedContractEvent<
      IdentityRevokedEvent.InputTuple,
      IdentityRevokedEvent.OutputTuple,
      IdentityRevokedEvent.OutputObject
    >;
    IdentityRevoked: TypedContractEvent<
      IdentityRevokedEvent.InputTuple,
      IdentityRevokedEvent.OutputTuple,
      IdentityRevokedEvent.OutputObject
    >;

    "IdentityVerified(address,uint16,string)": TypedContractEvent<
      IdentityVerifiedEvent.InputTuple,
      IdentityVerifiedEvent.OutputTuple,
      IdentityVerifiedEvent.OutputObject
    >;
    IdentityVerified: TypedContractEvent<
      IdentityVerifiedEvent.InputTuple,
      IdentityVerifiedEvent.OutputTuple,
      IdentityVerifiedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SelfRegistered(address)": TypedContractEvent<
      SelfRegisteredEvent.InputTuple,
      SelfRegisteredEvent.OutputTuple,
      SelfRegisteredEvent.OutputObject
    >;
    SelfRegistered: TypedContractEvent<
      SelfRegisteredEvent.InputTuple,
      SelfRegisteredEvent.OutputTuple,
      SelfRegisteredEvent.OutputObject
    >;
  };
}
