/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ComplianceRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addComplianceOperator"
      | "addTokenAgent"
      | "assetRestrictions"
      | "bindToken"
      | "blockJurisdiction"
      | "canTransfer"
      | "checkTransferAllowed"
      | "complianceOperators"
      | "created"
      | "destroyed"
      | "externalRegistry"
      | "getAssetRestrictions"
      | "getInvestorProfile"
      | "investors"
      | "isInvestorCompliant"
      | "isJurisdictionBlocked"
      | "isTokenAgent"
      | "isTokenBound"
      | "isVerifiedInATS"
      | "owner"
      | "purchaseTime"
      | "recordPurchase"
      | "removeComplianceOperator"
      | "removeExternalRegistry"
      | "removeInvestor"
      | "removeTokenAgent"
      | "renewKYC"
      | "renounceOwnership"
      | "setAssetRestrictions"
      | "setExternalRegistry"
      | "transferOwnership"
      | "transferred"
      | "unbindToken"
      | "unblockJurisdiction"
      | "updateAccreditation"
      | "whitelistInvestor"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccreditationUpdated"
      | "AssetRestrictionsSet"
      | "ComplianceOperatorAdded"
      | "ComplianceOperatorRemoved"
      | "ExternalRegistrySet"
      | "InvestorRemoved"
      | "InvestorWhitelisted"
      | "JurisdictionBlocked"
      | "JurisdictionUnblocked"
      | "KYCVerified"
      | "OwnershipTransferred"
      | "TokenAgentAdded"
      | "TokenAgentRemoved"
      | "TokenBound"
      | "TokenUnbound"
      | "TransferRestrictionUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addComplianceOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addTokenAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "assetRestrictions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "bindToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "blockJurisdiction",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "canTransfer",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkTransferAllowed",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "complianceOperators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "created",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "destroyed",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "externalRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAssetRestrictions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getInvestorProfile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "investors",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isInvestorCompliant",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isJurisdictionBlocked",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isTokenAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTokenBound",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerifiedInATS",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "purchaseTime",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordPurchase",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeComplianceOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeExternalRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeInvestor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeTokenAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renewKYC",
    values: [AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAssetRestrictions",
    values: [AddressLike, boolean, boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setExternalRegistry",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferred",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unbindToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unblockJurisdiction",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAccreditation",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistInvestor",
    values: [AddressLike, BytesLike, string, boolean, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addComplianceOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addTokenAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assetRestrictions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bindToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "blockJurisdiction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkTransferAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "complianceOperators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "created", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "destroyed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "externalRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAssetRestrictions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInvestorProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "investors", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isInvestorCompliant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isJurisdictionBlocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTokenAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTokenBound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isVerifiedInATS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "purchaseTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordPurchase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeComplianceOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeExternalRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeInvestor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeTokenAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "renewKYC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAssetRestrictions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExternalRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferred",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unbindToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unblockJurisdiction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAccreditation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistInvestor",
    data: BytesLike
  ): Result;
}

export namespace AccreditationUpdatedEvent {
  export type InputTuple = [investor: AddressLike, isAccredited: boolean];
  export type OutputTuple = [investor: string, isAccredited: boolean];
  export interface OutputObject {
    investor: string;
    isAccredited: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssetRestrictionsSetEvent {
  export type InputTuple = [
    asset: AddressLike,
    requiresKYC: boolean,
    requiresAccreditation: boolean
  ];
  export type OutputTuple = [
    asset: string,
    requiresKYC: boolean,
    requiresAccreditation: boolean
  ];
  export interface OutputObject {
    asset: string;
    requiresKYC: boolean;
    requiresAccreditation: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplianceOperatorAddedEvent {
  export type InputTuple = [operator: AddressLike];
  export type OutputTuple = [operator: string];
  export interface OutputObject {
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplianceOperatorRemovedEvent {
  export type InputTuple = [operator: AddressLike];
  export type OutputTuple = [operator: string];
  export interface OutputObject {
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExternalRegistrySetEvent {
  export type InputTuple = [asset: AddressLike, registry: AddressLike];
  export type OutputTuple = [asset: string, registry: string];
  export interface OutputObject {
    asset: string;
    registry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvestorRemovedEvent {
  export type InputTuple = [investor: AddressLike];
  export type OutputTuple = [investor: string];
  export interface OutputObject {
    investor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvestorWhitelistedEvent {
  export type InputTuple = [investor: AddressLike, kycHash: BytesLike];
  export type OutputTuple = [investor: string, kycHash: string];
  export interface OutputObject {
    investor: string;
    kycHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JurisdictionBlockedEvent {
  export type InputTuple = [asset: AddressLike, jurisdiction: string];
  export type OutputTuple = [asset: string, jurisdiction: string];
  export interface OutputObject {
    asset: string;
    jurisdiction: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JurisdictionUnblockedEvent {
  export type InputTuple = [asset: AddressLike, jurisdiction: string];
  export type OutputTuple = [asset: string, jurisdiction: string];
  export interface OutputObject {
    asset: string;
    jurisdiction: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KYCVerifiedEvent {
  export type InputTuple = [investor: AddressLike, expiryTime: BigNumberish];
  export type OutputTuple = [investor: string, expiryTime: bigint];
  export interface OutputObject {
    investor: string;
    expiryTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenAgentAddedEvent {
  export type InputTuple = [agent: AddressLike];
  export type OutputTuple = [agent: string];
  export interface OutputObject {
    agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenAgentRemovedEvent {
  export type InputTuple = [agent: AddressLike];
  export type OutputTuple = [agent: string];
  export interface OutputObject {
    agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenBoundEvent {
  export type InputTuple = [_token: AddressLike];
  export type OutputTuple = [_token: string];
  export interface OutputObject {
    _token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenUnboundEvent {
  export type InputTuple = [_token: AddressLike];
  export type OutputTuple = [_token: string];
  export interface OutputObject {
    _token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferRestrictionUpdatedEvent {
  export type InputTuple = [asset: AddressLike, maxAmount: BigNumberish];
  export type OutputTuple = [asset: string, maxAmount: bigint];
  export interface OutputObject {
    asset: string;
    maxAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ComplianceRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ComplianceRegistry;
  waitForDeployment(): Promise<this>;

  interface: ComplianceRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addComplianceOperator: TypedContractMethod<
    [operator: AddressLike],
    [void],
    "nonpayable"
  >;

  addTokenAgent: TypedContractMethod<
    [agent: AddressLike],
    [void],
    "nonpayable"
  >;

  assetRestrictions: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, boolean, bigint, bigint, boolean] & {
        requiresKYC: boolean;
        requiresAccreditation: boolean;
        minHoldingPeriod: bigint;
        maxTransferAmount: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  bindToken: TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;

  blockJurisdiction: TypedContractMethod<
    [asset: AddressLike, jurisdiction: string],
    [void],
    "nonpayable"
  >;

  canTransfer: TypedContractMethod<
    [_from: AddressLike, _to: AddressLike, _amount: BigNumberish],
    [boolean],
    "view"
  >;

  checkTransferAllowed: TypedContractMethod<
    [
      asset: AddressLike,
      from: AddressLike,
      to: AddressLike,
      amount: BigNumberish
    ],
    [[boolean, string] & { allowed: boolean; reason: string }],
    "view"
  >;

  complianceOperators: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  created: TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  destroyed: TypedContractMethod<
    [_from: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  externalRegistry: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getAssetRestrictions: TypedContractMethod<
    [asset: AddressLike],
    [
      [boolean, boolean, bigint, bigint, boolean] & {
        requiresKYC: boolean;
        requiresAccreditation: boolean;
        minHoldingPeriod: bigint;
        maxTransferAmount: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getInvestorProfile: TypedContractMethod<
    [investor: AddressLike],
    [
      [boolean, boolean, boolean, bigint, string] & {
        isWhitelisted: boolean;
        isKYCVerified: boolean;
        isAccredited: boolean;
        kycExpiryTime: bigint;
        jurisdiction: string;
      }
    ],
    "view"
  >;

  investors: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, boolean, boolean, bigint, string, bigint, bigint, string] & {
        isWhitelisted: boolean;
        isKYCVerified: boolean;
        isAccredited: boolean;
        kycExpiryTime: bigint;
        jurisdiction: string;
        maxTransferAmount: bigint;
        lastUpdateTime: bigint;
        kycHash: string;
      }
    ],
    "view"
  >;

  isInvestorCompliant: TypedContractMethod<
    [investor: AddressLike],
    [boolean],
    "view"
  >;

  isJurisdictionBlocked: TypedContractMethod<
    [asset: AddressLike, jurisdiction: string],
    [boolean],
    "view"
  >;

  isTokenAgent: TypedContractMethod<
    [_agentAddress: AddressLike],
    [boolean],
    "view"
  >;

  isTokenBound: TypedContractMethod<[_token: AddressLike], [boolean], "view">;

  isVerifiedInATS: TypedContractMethod<
    [asset: AddressLike, investor: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  purchaseTime: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  recordPurchase: TypedContractMethod<
    [asset: AddressLike, buyer: AddressLike],
    [void],
    "nonpayable"
  >;

  removeComplianceOperator: TypedContractMethod<
    [operator: AddressLike],
    [void],
    "nonpayable"
  >;

  removeExternalRegistry: TypedContractMethod<
    [asset: AddressLike],
    [void],
    "nonpayable"
  >;

  removeInvestor: TypedContractMethod<
    [investor: AddressLike],
    [void],
    "nonpayable"
  >;

  removeTokenAgent: TypedContractMethod<
    [agent: AddressLike],
    [void],
    "nonpayable"
  >;

  renewKYC: TypedContractMethod<
    [
      investor: AddressLike,
      newKycHash: BytesLike,
      validityPeriod: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAssetRestrictions: TypedContractMethod<
    [
      asset: AddressLike,
      requiresKYC: boolean,
      requiresAccreditation: boolean,
      minHoldingPeriod: BigNumberish,
      maxTransferAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setExternalRegistry: TypedContractMethod<
    [asset: AddressLike, identityRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  transferred: TypedContractMethod<
    [_from: AddressLike, _to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  unbindToken: TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;

  unblockJurisdiction: TypedContractMethod<
    [asset: AddressLike, jurisdiction: string],
    [void],
    "nonpayable"
  >;

  updateAccreditation: TypedContractMethod<
    [investor: AddressLike, isAccredited: boolean],
    [void],
    "nonpayable"
  >;

  whitelistInvestor: TypedContractMethod<
    [
      investor: AddressLike,
      kycHash: BytesLike,
      jurisdiction: string,
      isAccredited: boolean,
      kycValidityPeriod: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addComplianceOperator"
  ): TypedContractMethod<[operator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addTokenAgent"
  ): TypedContractMethod<[agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "assetRestrictions"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, boolean, bigint, bigint, boolean] & {
        requiresKYC: boolean;
        requiresAccreditation: boolean;
        minHoldingPeriod: bigint;
        maxTransferAmount: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "bindToken"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "blockJurisdiction"
  ): TypedContractMethod<
    [asset: AddressLike, jurisdiction: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "canTransfer"
  ): TypedContractMethod<
    [_from: AddressLike, _to: AddressLike, _amount: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkTransferAllowed"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      from: AddressLike,
      to: AddressLike,
      amount: BigNumberish
    ],
    [[boolean, string] & { allowed: boolean; reason: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "complianceOperators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "created"
  ): TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "destroyed"
  ): TypedContractMethod<
    [_from: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "externalRegistry"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getAssetRestrictions"
  ): TypedContractMethod<
    [asset: AddressLike],
    [
      [boolean, boolean, bigint, bigint, boolean] & {
        requiresKYC: boolean;
        requiresAccreditation: boolean;
        minHoldingPeriod: bigint;
        maxTransferAmount: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getInvestorProfile"
  ): TypedContractMethod<
    [investor: AddressLike],
    [
      [boolean, boolean, boolean, bigint, string] & {
        isWhitelisted: boolean;
        isKYCVerified: boolean;
        isAccredited: boolean;
        kycExpiryTime: bigint;
        jurisdiction: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "investors"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, boolean, boolean, bigint, string, bigint, bigint, string] & {
        isWhitelisted: boolean;
        isKYCVerified: boolean;
        isAccredited: boolean;
        kycExpiryTime: bigint;
        jurisdiction: string;
        maxTransferAmount: bigint;
        lastUpdateTime: bigint;
        kycHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isInvestorCompliant"
  ): TypedContractMethod<[investor: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isJurisdictionBlocked"
  ): TypedContractMethod<
    [asset: AddressLike, jurisdiction: string],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isTokenAgent"
  ): TypedContractMethod<[_agentAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isTokenBound"
  ): TypedContractMethod<[_token: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isVerifiedInATS"
  ): TypedContractMethod<
    [asset: AddressLike, investor: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "purchaseTime"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordPurchase"
  ): TypedContractMethod<
    [asset: AddressLike, buyer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeComplianceOperator"
  ): TypedContractMethod<[operator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeExternalRegistry"
  ): TypedContractMethod<[asset: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeInvestor"
  ): TypedContractMethod<[investor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeTokenAgent"
  ): TypedContractMethod<[agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renewKYC"
  ): TypedContractMethod<
    [
      investor: AddressLike,
      newKycHash: BytesLike,
      validityPeriod: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAssetRestrictions"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      requiresKYC: boolean,
      requiresAccreditation: boolean,
      minHoldingPeriod: BigNumberish,
      maxTransferAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setExternalRegistry"
  ): TypedContractMethod<
    [asset: AddressLike, identityRegistry: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferred"
  ): TypedContractMethod<
    [_from: AddressLike, _to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unbindToken"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unblockJurisdiction"
  ): TypedContractMethod<
    [asset: AddressLike, jurisdiction: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateAccreditation"
  ): TypedContractMethod<
    [investor: AddressLike, isAccredited: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "whitelistInvestor"
  ): TypedContractMethod<
    [
      investor: AddressLike,
      kycHash: BytesLike,
      jurisdiction: string,
      isAccredited: boolean,
      kycValidityPeriod: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AccreditationUpdated"
  ): TypedContractEvent<
    AccreditationUpdatedEvent.InputTuple,
    AccreditationUpdatedEvent.OutputTuple,
    AccreditationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AssetRestrictionsSet"
  ): TypedContractEvent<
    AssetRestrictionsSetEvent.InputTuple,
    AssetRestrictionsSetEvent.OutputTuple,
    AssetRestrictionsSetEvent.OutputObject
  >;
  getEvent(
    key: "ComplianceOperatorAdded"
  ): TypedContractEvent<
    ComplianceOperatorAddedEvent.InputTuple,
    ComplianceOperatorAddedEvent.OutputTuple,
    ComplianceOperatorAddedEvent.OutputObject
  >;
  getEvent(
    key: "ComplianceOperatorRemoved"
  ): TypedContractEvent<
    ComplianceOperatorRemovedEvent.InputTuple,
    ComplianceOperatorRemovedEvent.OutputTuple,
    ComplianceOperatorRemovedEvent.OutputObject
  >;
  getEvent(
    key: "ExternalRegistrySet"
  ): TypedContractEvent<
    ExternalRegistrySetEvent.InputTuple,
    ExternalRegistrySetEvent.OutputTuple,
    ExternalRegistrySetEvent.OutputObject
  >;
  getEvent(
    key: "InvestorRemoved"
  ): TypedContractEvent<
    InvestorRemovedEvent.InputTuple,
    InvestorRemovedEvent.OutputTuple,
    InvestorRemovedEvent.OutputObject
  >;
  getEvent(
    key: "InvestorWhitelisted"
  ): TypedContractEvent<
    InvestorWhitelistedEvent.InputTuple,
    InvestorWhitelistedEvent.OutputTuple,
    InvestorWhitelistedEvent.OutputObject
  >;
  getEvent(
    key: "JurisdictionBlocked"
  ): TypedContractEvent<
    JurisdictionBlockedEvent.InputTuple,
    JurisdictionBlockedEvent.OutputTuple,
    JurisdictionBlockedEvent.OutputObject
  >;
  getEvent(
    key: "JurisdictionUnblocked"
  ): TypedContractEvent<
    JurisdictionUnblockedEvent.InputTuple,
    JurisdictionUnblockedEvent.OutputTuple,
    JurisdictionUnblockedEvent.OutputObject
  >;
  getEvent(
    key: "KYCVerified"
  ): TypedContractEvent<
    KYCVerifiedEvent.InputTuple,
    KYCVerifiedEvent.OutputTuple,
    KYCVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TokenAgentAdded"
  ): TypedContractEvent<
    TokenAgentAddedEvent.InputTuple,
    TokenAgentAddedEvent.OutputTuple,
    TokenAgentAddedEvent.OutputObject
  >;
  getEvent(
    key: "TokenAgentRemoved"
  ): TypedContractEvent<
    TokenAgentRemovedEvent.InputTuple,
    TokenAgentRemovedEvent.OutputTuple,
    TokenAgentRemovedEvent.OutputObject
  >;
  getEvent(
    key: "TokenBound"
  ): TypedContractEvent<
    TokenBoundEvent.InputTuple,
    TokenBoundEvent.OutputTuple,
    TokenBoundEvent.OutputObject
  >;
  getEvent(
    key: "TokenUnbound"
  ): TypedContractEvent<
    TokenUnboundEvent.InputTuple,
    TokenUnboundEvent.OutputTuple,
    TokenUnboundEvent.OutputObject
  >;
  getEvent(
    key: "TransferRestrictionUpdated"
  ): TypedContractEvent<
    TransferRestrictionUpdatedEvent.InputTuple,
    TransferRestrictionUpdatedEvent.OutputTuple,
    TransferRestrictionUpdatedEvent.OutputObject
  >;

  filters: {
    "AccreditationUpdated(address,bool)": TypedContractEvent<
      AccreditationUpdatedEvent.InputTuple,
      AccreditationUpdatedEvent.OutputTuple,
      AccreditationUpdatedEvent.OutputObject
    >;
    AccreditationUpdated: TypedContractEvent<
      AccreditationUpdatedEvent.InputTuple,
      AccreditationUpdatedEvent.OutputTuple,
      AccreditationUpdatedEvent.OutputObject
    >;

    "AssetRestrictionsSet(address,bool,bool)": TypedContractEvent<
      AssetRestrictionsSetEvent.InputTuple,
      AssetRestrictionsSetEvent.OutputTuple,
      AssetRestrictionsSetEvent.OutputObject
    >;
    AssetRestrictionsSet: TypedContractEvent<
      AssetRestrictionsSetEvent.InputTuple,
      AssetRestrictionsSetEvent.OutputTuple,
      AssetRestrictionsSetEvent.OutputObject
    >;

    "ComplianceOperatorAdded(address)": TypedContractEvent<
      ComplianceOperatorAddedEvent.InputTuple,
      ComplianceOperatorAddedEvent.OutputTuple,
      ComplianceOperatorAddedEvent.OutputObject
    >;
    ComplianceOperatorAdded: TypedContractEvent<
      ComplianceOperatorAddedEvent.InputTuple,
      ComplianceOperatorAddedEvent.OutputTuple,
      ComplianceOperatorAddedEvent.OutputObject
    >;

    "ComplianceOperatorRemoved(address)": TypedContractEvent<
      ComplianceOperatorRemovedEvent.InputTuple,
      ComplianceOperatorRemovedEvent.OutputTuple,
      ComplianceOperatorRemovedEvent.OutputObject
    >;
    ComplianceOperatorRemoved: TypedContractEvent<
      ComplianceOperatorRemovedEvent.InputTuple,
      ComplianceOperatorRemovedEvent.OutputTuple,
      ComplianceOperatorRemovedEvent.OutputObject
    >;

    "ExternalRegistrySet(address,address)": TypedContractEvent<
      ExternalRegistrySetEvent.InputTuple,
      ExternalRegistrySetEvent.OutputTuple,
      ExternalRegistrySetEvent.OutputObject
    >;
    ExternalRegistrySet: TypedContractEvent<
      ExternalRegistrySetEvent.InputTuple,
      ExternalRegistrySetEvent.OutputTuple,
      ExternalRegistrySetEvent.OutputObject
    >;

    "InvestorRemoved(address)": TypedContractEvent<
      InvestorRemovedEvent.InputTuple,
      InvestorRemovedEvent.OutputTuple,
      InvestorRemovedEvent.OutputObject
    >;
    InvestorRemoved: TypedContractEvent<
      InvestorRemovedEvent.InputTuple,
      InvestorRemovedEvent.OutputTuple,
      InvestorRemovedEvent.OutputObject
    >;

    "InvestorWhitelisted(address,bytes32)": TypedContractEvent<
      InvestorWhitelistedEvent.InputTuple,
      InvestorWhitelistedEvent.OutputTuple,
      InvestorWhitelistedEvent.OutputObject
    >;
    InvestorWhitelisted: TypedContractEvent<
      InvestorWhitelistedEvent.InputTuple,
      InvestorWhitelistedEvent.OutputTuple,
      InvestorWhitelistedEvent.OutputObject
    >;

    "JurisdictionBlocked(address,string)": TypedContractEvent<
      JurisdictionBlockedEvent.InputTuple,
      JurisdictionBlockedEvent.OutputTuple,
      JurisdictionBlockedEvent.OutputObject
    >;
    JurisdictionBlocked: TypedContractEvent<
      JurisdictionBlockedEvent.InputTuple,
      JurisdictionBlockedEvent.OutputTuple,
      JurisdictionBlockedEvent.OutputObject
    >;

    "JurisdictionUnblocked(address,string)": TypedContractEvent<
      JurisdictionUnblockedEvent.InputTuple,
      JurisdictionUnblockedEvent.OutputTuple,
      JurisdictionUnblockedEvent.OutputObject
    >;
    JurisdictionUnblocked: TypedContractEvent<
      JurisdictionUnblockedEvent.InputTuple,
      JurisdictionUnblockedEvent.OutputTuple,
      JurisdictionUnblockedEvent.OutputObject
    >;

    "KYCVerified(address,uint256)": TypedContractEvent<
      KYCVerifiedEvent.InputTuple,
      KYCVerifiedEvent.OutputTuple,
      KYCVerifiedEvent.OutputObject
    >;
    KYCVerified: TypedContractEvent<
      KYCVerifiedEvent.InputTuple,
      KYCVerifiedEvent.OutputTuple,
      KYCVerifiedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TokenAgentAdded(address)": TypedContractEvent<
      TokenAgentAddedEvent.InputTuple,
      TokenAgentAddedEvent.OutputTuple,
      TokenAgentAddedEvent.OutputObject
    >;
    TokenAgentAdded: TypedContractEvent<
      TokenAgentAddedEvent.InputTuple,
      TokenAgentAddedEvent.OutputTuple,
      TokenAgentAddedEvent.OutputObject
    >;

    "TokenAgentRemoved(address)": TypedContractEvent<
      TokenAgentRemovedEvent.InputTuple,
      TokenAgentRemovedEvent.OutputTuple,
      TokenAgentRemovedEvent.OutputObject
    >;
    TokenAgentRemoved: TypedContractEvent<
      TokenAgentRemovedEvent.InputTuple,
      TokenAgentRemovedEvent.OutputTuple,
      TokenAgentRemovedEvent.OutputObject
    >;

    "TokenBound(address)": TypedContractEvent<
      TokenBoundEvent.InputTuple,
      TokenBoundEvent.OutputTuple,
      TokenBoundEvent.OutputObject
    >;
    TokenBound: TypedContractEvent<
      TokenBoundEvent.InputTuple,
      TokenBoundEvent.OutputTuple,
      TokenBoundEvent.OutputObject
    >;

    "TokenUnbound(address)": TypedContractEvent<
      TokenUnboundEvent.InputTuple,
      TokenUnboundEvent.OutputTuple,
      TokenUnboundEvent.OutputObject
    >;
    TokenUnbound: TypedContractEvent<
      TokenUnboundEvent.InputTuple,
      TokenUnboundEvent.OutputTuple,
      TokenUnboundEvent.OutputObject
    >;

    "TransferRestrictionUpdated(address,uint256)": TypedContractEvent<
      TransferRestrictionUpdatedEvent.InputTuple,
      TransferRestrictionUpdatedEvent.OutputTuple,
      TransferRestrictionUpdatedEvent.OutputObject
    >;
    TransferRestrictionUpdated: TypedContractEvent<
      TransferRestrictionUpdatedEvent.InputTuple,
      TransferRestrictionUpdatedEvent.OutputTuple,
      TransferRestrictionUpdatedEvent.OutputObject
    >;
  };
}
