/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface LiquidityVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PRECISION"
      | "claimRewards"
      | "depositRewards"
      | "emergencyWithdraw"
      | "getPoolCount"
      | "getPoolId"
      | "getPoolInfo"
      | "getStakeInfo"
      | "getVaultRewardBalance"
      | "initializePool"
      | "owner"
      | "pendingRewards"
      | "poolIds"
      | "pools"
      | "renounceOwnership"
      | "stake"
      | "stakes"
      | "transferOwnership"
      | "unstake"
      | "updateRewardRate"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EmergencyWithdraw"
      | "OwnershipTransferred"
      | "PoolInitialized"
      | "RewardRateUpdated"
      | "RewardsClaimed"
      | "RewardsDeposited"
      | "Staked"
      | "Unstaked"
  ): EventFragment;

  encodeFunctionData(functionFragment: "PRECISION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimRewards",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositRewards",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolInfo",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStakeInfo",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultRewardBalance",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initializePool",
    values: [BytesLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingRewards",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "poolIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pools", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stake",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakes",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unstake",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRewardRate",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "PRECISION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPoolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPoolInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStakeInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultRewardBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "poolIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pools", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stakes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unstake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateRewardRate",
    data: BytesLike
  ): Result;
}

export namespace EmergencyWithdrawEvent {
  export type InputTuple = [
    poolId: BytesLike,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [poolId: string, user: string, amount: bigint];
  export interface OutputObject {
    poolId: string;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolInitializedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    stakedToken: AddressLike,
    rewardToken: AddressLike,
    rewardRate: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    stakedToken: string,
    rewardToken: string,
    rewardRate: bigint
  ];
  export interface OutputObject {
    poolId: string;
    stakedToken: string;
    rewardToken: string;
    rewardRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardRateUpdatedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    oldRate: BigNumberish,
    newRate: BigNumberish
  ];
  export type OutputTuple = [poolId: string, oldRate: bigint, newRate: bigint];
  export interface OutputObject {
    poolId: string;
    oldRate: bigint;
    newRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsClaimedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [poolId: string, user: string, amount: bigint];
  export interface OutputObject {
    poolId: string;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsDepositedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    rewardToken: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    rewardToken: string,
    amount: bigint
  ];
  export interface OutputObject {
    poolId: string;
    rewardToken: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [poolId: string, user: string, amount: bigint];
  export interface OutputObject {
    poolId: string;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnstakedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [poolId: string, user: string, amount: bigint];
  export interface OutputObject {
    poolId: string;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LiquidityVault extends BaseContract {
  connect(runner?: ContractRunner | null): LiquidityVault;
  waitForDeployment(): Promise<this>;

  interface: LiquidityVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PRECISION: TypedContractMethod<[], [bigint], "view">;

  claimRewards: TypedContractMethod<[poolId: BytesLike], [void], "nonpayable">;

  depositRewards: TypedContractMethod<
    [poolId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<
    [poolId: BytesLike],
    [void],
    "nonpayable"
  >;

  getPoolCount: TypedContractMethod<[], [bigint], "view">;

  getPoolId: TypedContractMethod<[index: BigNumberish], [string], "view">;

  getPoolInfo: TypedContractMethod<
    [poolId: BytesLike],
    [
      [string, string, bigint, bigint, bigint, boolean] & {
        stakedToken: string;
        rewardToken: string;
        rewardRatePerSecond: bigint;
        totalStakedAmount: bigint;
        accumulatedRewardPerShare: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getStakeInfo: TypedContractMethod<
    [poolId: BytesLike, user: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        amount: bigint;
        rewardDebt: bigint;
        lastStakeTime: bigint;
        pendingRewardsAmount: bigint;
      }
    ],
    "view"
  >;

  getVaultRewardBalance: TypedContractMethod<
    [poolId: BytesLike],
    [bigint],
    "view"
  >;

  initializePool: TypedContractMethod<
    [
      poolId: BytesLike,
      stakedToken: AddressLike,
      rewardToken: AddressLike,
      rewardRate: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pendingRewards: TypedContractMethod<
    [poolId: BytesLike, user: AddressLike],
    [bigint],
    "view"
  >;

  poolIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  pools: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean] & {
        stakedToken: string;
        rewardToken: string;
        rewardRate: bigint;
        accRewardPerShare: bigint;
        lastRewardTime: bigint;
        totalStaked: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  stake: TypedContractMethod<
    [poolId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  stakes: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        amount: bigint;
        rewardDebt: bigint;
        lastStakeTime: bigint;
        pendingRewards: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unstake: TypedContractMethod<
    [poolId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateRewardRate: TypedContractMethod<
    [poolId: BytesLike, newRate: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PRECISION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimRewards"
  ): TypedContractMethod<[poolId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositRewards"
  ): TypedContractMethod<
    [poolId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[poolId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getPoolCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPoolId"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getPoolInfo"
  ): TypedContractMethod<
    [poolId: BytesLike],
    [
      [string, string, bigint, bigint, bigint, boolean] & {
        stakedToken: string;
        rewardToken: string;
        rewardRatePerSecond: bigint;
        totalStakedAmount: bigint;
        accumulatedRewardPerShare: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStakeInfo"
  ): TypedContractMethod<
    [poolId: BytesLike, user: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        amount: bigint;
        rewardDebt: bigint;
        lastStakeTime: bigint;
        pendingRewardsAmount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVaultRewardBalance"
  ): TypedContractMethod<[poolId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "initializePool"
  ): TypedContractMethod<
    [
      poolId: BytesLike,
      stakedToken: AddressLike,
      rewardToken: AddressLike,
      rewardRate: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingRewards"
  ): TypedContractMethod<
    [poolId: BytesLike, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "poolIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "pools"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean] & {
        stakedToken: string;
        rewardToken: string;
        rewardRate: bigint;
        accRewardPerShare: bigint;
        lastRewardTime: bigint;
        totalStaked: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<
    [poolId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stakes"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        amount: bigint;
        rewardDebt: bigint;
        lastStakeTime: bigint;
        pendingRewards: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstake"
  ): TypedContractMethod<
    [poolId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateRewardRate"
  ): TypedContractMethod<
    [poolId: BytesLike, newRate: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "EmergencyWithdraw"
  ): TypedContractEvent<
    EmergencyWithdrawEvent.InputTuple,
    EmergencyWithdrawEvent.OutputTuple,
    EmergencyWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PoolInitialized"
  ): TypedContractEvent<
    PoolInitializedEvent.InputTuple,
    PoolInitializedEvent.OutputTuple,
    PoolInitializedEvent.OutputObject
  >;
  getEvent(
    key: "RewardRateUpdated"
  ): TypedContractEvent<
    RewardRateUpdatedEvent.InputTuple,
    RewardRateUpdatedEvent.OutputTuple,
    RewardRateUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsClaimed"
  ): TypedContractEvent<
    RewardsClaimedEvent.InputTuple,
    RewardsClaimedEvent.OutputTuple,
    RewardsClaimedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsDeposited"
  ): TypedContractEvent<
    RewardsDepositedEvent.InputTuple,
    RewardsDepositedEvent.OutputTuple,
    RewardsDepositedEvent.OutputObject
  >;
  getEvent(
    key: "Staked"
  ): TypedContractEvent<
    StakedEvent.InputTuple,
    StakedEvent.OutputTuple,
    StakedEvent.OutputObject
  >;
  getEvent(
    key: "Unstaked"
  ): TypedContractEvent<
    UnstakedEvent.InputTuple,
    UnstakedEvent.OutputTuple,
    UnstakedEvent.OutputObject
  >;

  filters: {
    "EmergencyWithdraw(bytes32,address,uint256)": TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;
    EmergencyWithdraw: TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PoolInitialized(bytes32,address,address,uint256)": TypedContractEvent<
      PoolInitializedEvent.InputTuple,
      PoolInitializedEvent.OutputTuple,
      PoolInitializedEvent.OutputObject
    >;
    PoolInitialized: TypedContractEvent<
      PoolInitializedEvent.InputTuple,
      PoolInitializedEvent.OutputTuple,
      PoolInitializedEvent.OutputObject
    >;

    "RewardRateUpdated(bytes32,uint256,uint256)": TypedContractEvent<
      RewardRateUpdatedEvent.InputTuple,
      RewardRateUpdatedEvent.OutputTuple,
      RewardRateUpdatedEvent.OutputObject
    >;
    RewardRateUpdated: TypedContractEvent<
      RewardRateUpdatedEvent.InputTuple,
      RewardRateUpdatedEvent.OutputTuple,
      RewardRateUpdatedEvent.OutputObject
    >;

    "RewardsClaimed(bytes32,address,uint256)": TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;
    RewardsClaimed: TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;

    "RewardsDeposited(bytes32,address,uint256)": TypedContractEvent<
      RewardsDepositedEvent.InputTuple,
      RewardsDepositedEvent.OutputTuple,
      RewardsDepositedEvent.OutputObject
    >;
    RewardsDeposited: TypedContractEvent<
      RewardsDepositedEvent.InputTuple,
      RewardsDepositedEvent.OutputTuple,
      RewardsDepositedEvent.OutputObject
    >;

    "Staked(bytes32,address,uint256)": TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;
    Staked: TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;

    "Unstaked(bytes32,address,uint256)": TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;
    Unstaked: TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;
  };
}
