/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RWATokenInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FAUCET_AMOUNT"
      | "addAgent"
      | "allowance"
      | "appraisalValue"
      | "approve"
      | "assetDescription"
      | "balanceOf"
      | "batchBurn"
      | "batchMint"
      | "batchSetAddressFrozen"
      | "batchTransfer"
      | "burn"
      | "compliance"
      | "decimals"
      | "demoModeEnabled"
      | "faucetMint"
      | "forcedTransfer"
      | "freezePartialTokens"
      | "getFrozenTokens"
      | "identityRegistry"
      | "isAgent"
      | "isFrozen"
      | "lastAppraisalTime"
      | "mint"
      | "name"
      | "onchainID"
      | "owner"
      | "pause"
      | "paused"
      | "recoveryAddress"
      | "removeAgent"
      | "renounceOwnership"
      | "setAddressFrozen"
      | "setCompliance"
      | "setDemoMode"
      | "setIdentityRegistry"
      | "setOnchainID"
      | "symbol"
      | "totalSupply"
      | "transfer"
      | "transferFrom"
      | "transferOwnership"
      | "unfreezePartialTokens"
      | "unpause"
      | "updateAppraisal"
      | "version"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddressFrozen"
      | "AgentAdded"
      | "AgentRemoved"
      | "AppraisalUpdated"
      | "Approval"
      | "ComplianceAdded"
      | "IdentityRegistryAdded"
      | "OwnershipTransferred"
      | "Paused"
      | "RecoverySuccess"
      | "TokensFrozen"
      | "TokensUnfrozen"
      | "Transfer"
      | "Unpaused"
      | "UpdatedTokenInformation"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "FAUCET_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "appraisalValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "assetDescription",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchBurn",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchMint",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchSetAddressFrozen",
    values: [AddressLike[], boolean[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchTransfer",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "burn",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "compliance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "demoModeEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "faucetMint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "forcedTransfer",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "freezePartialTokens",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFrozenTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "identityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isFrozen",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastAppraisalTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "onchainID", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recoveryAddress",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAddressFrozen",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setCompliance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDemoMode",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setIdentityRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setOnchainID",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unfreezePartialTokens",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateAppraisal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "FAUCET_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addAgent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "appraisalValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "assetDescription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "batchBurn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "batchMint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchSetAddressFrozen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "compliance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "demoModeEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "faucetMint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "forcedTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "freezePartialTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFrozenTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "identityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isAgent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isFrozen", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastAppraisalTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "onchainID", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recoveryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAddressFrozen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCompliance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDemoMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setIdentityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOnchainID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unfreezePartialTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateAppraisal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
}

export namespace AddressFrozenEvent {
  export type InputTuple = [
    userAddress: AddressLike,
    isFrozen: boolean,
    owner: AddressLike
  ];
  export type OutputTuple = [
    userAddress: string,
    isFrozen: boolean,
    owner: string
  ];
  export interface OutputObject {
    userAddress: string;
    isFrozen: boolean;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentAddedEvent {
  export type InputTuple = [agent: AddressLike];
  export type OutputTuple = [agent: string];
  export interface OutputObject {
    agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRemovedEvent {
  export type InputTuple = [agent: AddressLike];
  export type OutputTuple = [agent: string];
  export interface OutputObject {
    agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AppraisalUpdatedEvent {
  export type InputTuple = [oldValue: BigNumberish, newValue: BigNumberish];
  export type OutputTuple = [oldValue: bigint, newValue: bigint];
  export interface OutputObject {
    oldValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    spender: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [owner: string, spender: string, value: bigint];
  export interface OutputObject {
    owner: string;
    spender: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplianceAddedEvent {
  export type InputTuple = [compliance: AddressLike];
  export type OutputTuple = [compliance: string];
  export interface OutputObject {
    compliance: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityRegistryAddedEvent {
  export type InputTuple = [identityRegistry: AddressLike];
  export type OutputTuple = [identityRegistry: string];
  export interface OutputObject {
    identityRegistry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [userAddress: AddressLike];
  export type OutputTuple = [userAddress: string];
  export interface OutputObject {
    userAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecoverySuccessEvent {
  export type InputTuple = [
    lostWallet: AddressLike,
    newWallet: AddressLike,
    investorOnchainID: AddressLike
  ];
  export type OutputTuple = [
    lostWallet: string,
    newWallet: string,
    investorOnchainID: string
  ];
  export interface OutputObject {
    lostWallet: string;
    newWallet: string;
    investorOnchainID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensFrozenEvent {
  export type InputTuple = [userAddress: AddressLike, amount: BigNumberish];
  export type OutputTuple = [userAddress: string, amount: bigint];
  export interface OutputObject {
    userAddress: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensUnfrozenEvent {
  export type InputTuple = [userAddress: AddressLike, amount: BigNumberish];
  export type OutputTuple = [userAddress: string, amount: bigint];
  export interface OutputObject {
    userAddress: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, value: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [userAddress: AddressLike];
  export type OutputTuple = [userAddress: string];
  export interface OutputObject {
    userAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdatedTokenInformationEvent {
  export type InputTuple = [
    newName: string,
    newSymbol: string,
    newDecimals: BigNumberish,
    newVersion: string,
    newOnchainID: AddressLike
  ];
  export type OutputTuple = [
    newName: string,
    newSymbol: string,
    newDecimals: bigint,
    newVersion: string,
    newOnchainID: string
  ];
  export interface OutputObject {
    newName: string;
    newSymbol: string;
    newDecimals: bigint;
    newVersion: string;
    newOnchainID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RWAToken extends BaseContract {
  connect(runner?: ContractRunner | null): RWAToken;
  waitForDeployment(): Promise<this>;

  interface: RWATokenInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FAUCET_AMOUNT: TypedContractMethod<[], [bigint], "view">;

  addAgent: TypedContractMethod<[agent: AddressLike], [void], "nonpayable">;

  allowance: TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;

  appraisalValue: TypedContractMethod<[], [bigint], "view">;

  approve: TypedContractMethod<
    [spender: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  assetDescription: TypedContractMethod<[], [string], "view">;

  balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  batchBurn: TypedContractMethod<
    [addresses: AddressLike[], amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  batchMint: TypedContractMethod<
    [toList: AddressLike[], amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  batchSetAddressFrozen: TypedContractMethod<
    [addresses: AddressLike[], freeze: boolean[]],
    [void],
    "nonpayable"
  >;

  batchTransfer: TypedContractMethod<
    [toList: AddressLike[], amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  burn: TypedContractMethod<
    [from: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  compliance: TypedContractMethod<[], [string], "view">;

  decimals: TypedContractMethod<[], [bigint], "view">;

  demoModeEnabled: TypedContractMethod<[], [boolean], "view">;

  faucetMint: TypedContractMethod<[], [void], "nonpayable">;

  forcedTransfer: TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  freezePartialTokens: TypedContractMethod<
    [userAddress: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFrozenTokens: TypedContractMethod<
    [userAddress: AddressLike],
    [bigint],
    "view"
  >;

  identityRegistry: TypedContractMethod<[], [string], "view">;

  isAgent: TypedContractMethod<[agent: AddressLike], [boolean], "view">;

  isFrozen: TypedContractMethod<[userAddress: AddressLike], [boolean], "view">;

  lastAppraisalTime: TypedContractMethod<[], [bigint], "view">;

  mint: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  onchainID: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  recoveryAddress: TypedContractMethod<
    [
      lostWallet: AddressLike,
      newWallet: AddressLike,
      investorOnchainID: AddressLike
    ],
    [boolean],
    "nonpayable"
  >;

  removeAgent: TypedContractMethod<[agent: AddressLike], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAddressFrozen: TypedContractMethod<
    [userAddress: AddressLike, freeze: boolean],
    [void],
    "nonpayable"
  >;

  setCompliance: TypedContractMethod<
    [_newCompliance: AddressLike],
    [void],
    "nonpayable"
  >;

  setDemoMode: TypedContractMethod<[enabled: boolean], [void], "nonpayable">;

  setIdentityRegistry: TypedContractMethod<
    [_newIdentityRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  setOnchainID: TypedContractMethod<
    [_newOnchainID: AddressLike],
    [void],
    "nonpayable"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transfer: TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unfreezePartialTokens: TypedContractMethod<
    [userAddress: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateAppraisal: TypedContractMethod<
    [newAppraisal: BigNumberish],
    [void],
    "nonpayable"
  >;

  version: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FAUCET_AMOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addAgent"
  ): TypedContractMethod<[agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "appraisalValue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [spender: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "assetDescription"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "batchBurn"
  ): TypedContractMethod<
    [addresses: AddressLike[], amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchMint"
  ): TypedContractMethod<
    [toList: AddressLike[], amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchSetAddressFrozen"
  ): TypedContractMethod<
    [addresses: AddressLike[], freeze: boolean[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchTransfer"
  ): TypedContractMethod<
    [toList: AddressLike[], amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "burn"
  ): TypedContractMethod<
    [from: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "compliance"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "demoModeEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "faucetMint"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "forcedTransfer"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "freezePartialTokens"
  ): TypedContractMethod<
    [userAddress: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getFrozenTokens"
  ): TypedContractMethod<[userAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "identityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isAgent"
  ): TypedContractMethod<[agent: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isFrozen"
  ): TypedContractMethod<[userAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastAppraisalTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "mint"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "onchainID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "recoveryAddress"
  ): TypedContractMethod<
    [
      lostWallet: AddressLike,
      newWallet: AddressLike,
      investorOnchainID: AddressLike
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeAgent"
  ): TypedContractMethod<[agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAddressFrozen"
  ): TypedContractMethod<
    [userAddress: AddressLike, freeze: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCompliance"
  ): TypedContractMethod<[_newCompliance: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDemoMode"
  ): TypedContractMethod<[enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setIdentityRegistry"
  ): TypedContractMethod<
    [_newIdentityRegistry: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setOnchainID"
  ): TypedContractMethod<[_newOnchainID: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unfreezePartialTokens"
  ): TypedContractMethod<
    [userAddress: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateAppraisal"
  ): TypedContractMethod<[newAppraisal: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AddressFrozen"
  ): TypedContractEvent<
    AddressFrozenEvent.InputTuple,
    AddressFrozenEvent.OutputTuple,
    AddressFrozenEvent.OutputObject
  >;
  getEvent(
    key: "AgentAdded"
  ): TypedContractEvent<
    AgentAddedEvent.InputTuple,
    AgentAddedEvent.OutputTuple,
    AgentAddedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRemoved"
  ): TypedContractEvent<
    AgentRemovedEvent.InputTuple,
    AgentRemovedEvent.OutputTuple,
    AgentRemovedEvent.OutputObject
  >;
  getEvent(
    key: "AppraisalUpdated"
  ): TypedContractEvent<
    AppraisalUpdatedEvent.InputTuple,
    AppraisalUpdatedEvent.OutputTuple,
    AppraisalUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "ComplianceAdded"
  ): TypedContractEvent<
    ComplianceAddedEvent.InputTuple,
    ComplianceAddedEvent.OutputTuple,
    ComplianceAddedEvent.OutputObject
  >;
  getEvent(
    key: "IdentityRegistryAdded"
  ): TypedContractEvent<
    IdentityRegistryAddedEvent.InputTuple,
    IdentityRegistryAddedEvent.OutputTuple,
    IdentityRegistryAddedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RecoverySuccess"
  ): TypedContractEvent<
    RecoverySuccessEvent.InputTuple,
    RecoverySuccessEvent.OutputTuple,
    RecoverySuccessEvent.OutputObject
  >;
  getEvent(
    key: "TokensFrozen"
  ): TypedContractEvent<
    TokensFrozenEvent.InputTuple,
    TokensFrozenEvent.OutputTuple,
    TokensFrozenEvent.OutputObject
  >;
  getEvent(
    key: "TokensUnfrozen"
  ): TypedContractEvent<
    TokensUnfrozenEvent.InputTuple,
    TokensUnfrozenEvent.OutputTuple,
    TokensUnfrozenEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "UpdatedTokenInformation"
  ): TypedContractEvent<
    UpdatedTokenInformationEvent.InputTuple,
    UpdatedTokenInformationEvent.OutputTuple,
    UpdatedTokenInformationEvent.OutputObject
  >;

  filters: {
    "AddressFrozen(address,bool,address)": TypedContractEvent<
      AddressFrozenEvent.InputTuple,
      AddressFrozenEvent.OutputTuple,
      AddressFrozenEvent.OutputObject
    >;
    AddressFrozen: TypedContractEvent<
      AddressFrozenEvent.InputTuple,
      AddressFrozenEvent.OutputTuple,
      AddressFrozenEvent.OutputObject
    >;

    "AgentAdded(address)": TypedContractEvent<
      AgentAddedEvent.InputTuple,
      AgentAddedEvent.OutputTuple,
      AgentAddedEvent.OutputObject
    >;
    AgentAdded: TypedContractEvent<
      AgentAddedEvent.InputTuple,
      AgentAddedEvent.OutputTuple,
      AgentAddedEvent.OutputObject
    >;

    "AgentRemoved(address)": TypedContractEvent<
      AgentRemovedEvent.InputTuple,
      AgentRemovedEvent.OutputTuple,
      AgentRemovedEvent.OutputObject
    >;
    AgentRemoved: TypedContractEvent<
      AgentRemovedEvent.InputTuple,
      AgentRemovedEvent.OutputTuple,
      AgentRemovedEvent.OutputObject
    >;

    "AppraisalUpdated(uint256,uint256)": TypedContractEvent<
      AppraisalUpdatedEvent.InputTuple,
      AppraisalUpdatedEvent.OutputTuple,
      AppraisalUpdatedEvent.OutputObject
    >;
    AppraisalUpdated: TypedContractEvent<
      AppraisalUpdatedEvent.InputTuple,
      AppraisalUpdatedEvent.OutputTuple,
      AppraisalUpdatedEvent.OutputObject
    >;

    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "ComplianceAdded(address)": TypedContractEvent<
      ComplianceAddedEvent.InputTuple,
      ComplianceAddedEvent.OutputTuple,
      ComplianceAddedEvent.OutputObject
    >;
    ComplianceAdded: TypedContractEvent<
      ComplianceAddedEvent.InputTuple,
      ComplianceAddedEvent.OutputTuple,
      ComplianceAddedEvent.OutputObject
    >;

    "IdentityRegistryAdded(address)": TypedContractEvent<
      IdentityRegistryAddedEvent.InputTuple,
      IdentityRegistryAddedEvent.OutputTuple,
      IdentityRegistryAddedEvent.OutputObject
    >;
    IdentityRegistryAdded: TypedContractEvent<
      IdentityRegistryAddedEvent.InputTuple,
      IdentityRegistryAddedEvent.OutputTuple,
      IdentityRegistryAddedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RecoverySuccess(address,address,address)": TypedContractEvent<
      RecoverySuccessEvent.InputTuple,
      RecoverySuccessEvent.OutputTuple,
      RecoverySuccessEvent.OutputObject
    >;
    RecoverySuccess: TypedContractEvent<
      RecoverySuccessEvent.InputTuple,
      RecoverySuccessEvent.OutputTuple,
      RecoverySuccessEvent.OutputObject
    >;

    "TokensFrozen(address,uint256)": TypedContractEvent<
      TokensFrozenEvent.InputTuple,
      TokensFrozenEvent.OutputTuple,
      TokensFrozenEvent.OutputObject
    >;
    TokensFrozen: TypedContractEvent<
      TokensFrozenEvent.InputTuple,
      TokensFrozenEvent.OutputTuple,
      TokensFrozenEvent.OutputObject
    >;

    "TokensUnfrozen(address,uint256)": TypedContractEvent<
      TokensUnfrozenEvent.InputTuple,
      TokensUnfrozenEvent.OutputTuple,
      TokensUnfrozenEvent.OutputObject
    >;
    TokensUnfrozen: TypedContractEvent<
      TokensUnfrozenEvent.InputTuple,
      TokensUnfrozenEvent.OutputTuple,
      TokensUnfrozenEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "UpdatedTokenInformation(string,string,uint8,string,address)": TypedContractEvent<
      UpdatedTokenInformationEvent.InputTuple,
      UpdatedTokenInformationEvent.OutputTuple,
      UpdatedTokenInformationEvent.OutputObject
    >;
    UpdatedTokenInformation: TypedContractEvent<
      UpdatedTokenInformationEvent.InputTuple,
      UpdatedTokenInformationEvent.OutputTuple,
      UpdatedTokenInformationEvent.OutputObject
    >;
  };
}
