/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TreasuryManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "APPROVER_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "EMERGENCY_ROLE"
      | "TREASURER_ROLE"
      | "approveWithdrawal"
      | "cancelWithdrawal"
      | "deposit"
      | "executeWithdrawal"
      | "getAccountingInfo"
      | "getRoleAdmin"
      | "getTreasuryBalance"
      | "getWithdrawalRequest"
      | "grantRole"
      | "hasApproved"
      | "hasRole"
      | "nextRequestId"
      | "paused"
      | "renounceRole"
      | "requestWithdrawal"
      | "requiredApprovals"
      | "revokeRole"
      | "setRequiredApprovals"
      | "setTimelockDuration"
      | "setWithdrawalLimit"
      | "supportsInterface"
      | "timelockDuration"
      | "togglePause"
      | "totalDeposited"
      | "totalWithdrawn"
      | "withdrawalLimits"
      | "withdrawalRequests"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Deposited"
      | "EmergencyPauseToggled"
      | "KMSSignatureRecorded"
      | "RequiredApprovalsUpdated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "TimelockDurationUpdated"
      | "WithdrawalApproved"
      | "WithdrawalCancelled"
      | "WithdrawalExecuted"
      | "WithdrawalLimitUpdated"
      | "WithdrawalRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "APPROVER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EMERGENCY_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TREASURER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveWithdrawal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelWithdrawal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeWithdrawal",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccountingInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTreasuryBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWithdrawalRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasApproved",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextRequestId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestWithdrawal",
    values: [AddressLike, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "requiredApprovals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRequiredApprovals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTimelockDuration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setWithdrawalLimit",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "timelockDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "togglePause",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalDeposited",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalWithdrawn",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalLimits",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalRequests",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "APPROVER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EMERGENCY_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TREASURER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccountingInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTreasuryBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWithdrawalRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextRequestId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requiredApprovals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setRequiredApprovals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTimelockDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWithdrawalLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timelockDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "togglePause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalDeposited",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalWithdrawn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalLimits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalRequests",
    data: BytesLike
  ): Result;
}

export namespace DepositedEvent {
  export type InputTuple = [
    token: AddressLike,
    from: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    from: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    token: string;
    from: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyPauseToggledEvent {
  export type InputTuple = [isPaused: boolean];
  export type OutputTuple = [isPaused: boolean];
  export interface OutputObject {
    isPaused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KMSSignatureRecordedEvent {
  export type InputTuple = [requestId: BigNumberish, signatureHash: BytesLike];
  export type OutputTuple = [requestId: bigint, signatureHash: string];
  export interface OutputObject {
    requestId: bigint;
    signatureHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequiredApprovalsUpdatedEvent {
  export type InputTuple = [oldValue: BigNumberish, newValue: BigNumberish];
  export type OutputTuple = [oldValue: bigint, newValue: bigint];
  export interface OutputObject {
    oldValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimelockDurationUpdatedEvent {
  export type InputTuple = [oldValue: BigNumberish, newValue: BigNumberish];
  export type OutputTuple = [oldValue: bigint, newValue: bigint];
  export interface OutputObject {
    oldValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalApprovedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    approver: AddressLike,
    approvalCount: BigNumberish
  ];
  export type OutputTuple = [
    requestId: bigint,
    approver: string,
    approvalCount: bigint
  ];
  export interface OutputObject {
    requestId: bigint;
    approver: string;
    approvalCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalCancelledEvent {
  export type InputTuple = [requestId: BigNumberish, cancelledBy: AddressLike];
  export type OutputTuple = [requestId: bigint, cancelledBy: string];
  export interface OutputObject {
    requestId: bigint;
    cancelledBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalExecutedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    token: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish,
    kmsSignature: BytesLike
  ];
  export type OutputTuple = [
    requestId: bigint,
    token: string,
    recipient: string,
    amount: bigint,
    kmsSignature: string
  ];
  export interface OutputObject {
    requestId: bigint;
    token: string;
    recipient: string;
    amount: bigint;
    kmsSignature: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalLimitUpdatedEvent {
  export type InputTuple = [token: AddressLike, newLimit: BigNumberish];
  export type OutputTuple = [token: string, newLimit: bigint];
  export interface OutputObject {
    token: string;
    newLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalRequestedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    token: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    requestId: bigint,
    token: string,
    recipient: string,
    amount: bigint,
    reason: string
  ];
  export interface OutputObject {
    requestId: bigint;
    token: string;
    recipient: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TreasuryManager extends BaseContract {
  connect(runner?: ContractRunner | null): TreasuryManager;
  waitForDeployment(): Promise<this>;

  interface: TreasuryManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  APPROVER_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  EMERGENCY_ROLE: TypedContractMethod<[], [string], "view">;

  TREASURER_ROLE: TypedContractMethod<[], [string], "view">;

  approveWithdrawal: TypedContractMethod<
    [requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelWithdrawal: TypedContractMethod<
    [requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  deposit: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "payable"
  >;

  executeWithdrawal: TypedContractMethod<
    [requestId: BigNumberish, kmsSignature: BytesLike],
    [void],
    "nonpayable"
  >;

  getAccountingInfo: TypedContractMethod<
    [token: AddressLike],
    [
      [bigint, bigint, bigint] & {
        deposited: bigint;
        withdrawn: bigint;
        currentBalance: bigint;
      }
    ],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getTreasuryBalance: TypedContractMethod<
    [token: AddressLike],
    [bigint],
    "view"
  >;

  getWithdrawalRequest: TypedContractMethod<
    [requestId: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string
      ] & {
        token: string;
        recipient: string;
        amount: bigint;
        requestTime: bigint;
        executeAfter: bigint;
        approvalCount: bigint;
        executed: boolean;
        cancelled: boolean;
        reason: string;
      }
    ],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasApproved: TypedContractMethod<
    [requestId: BigNumberish, approver: AddressLike],
    [boolean],
    "view"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  nextRequestId: TypedContractMethod<[], [bigint], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  requestWithdrawal: TypedContractMethod<
    [
      token: AddressLike,
      recipient: AddressLike,
      amount: BigNumberish,
      reason: string
    ],
    [bigint],
    "nonpayable"
  >;

  requiredApprovals: TypedContractMethod<[], [bigint], "view">;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setRequiredApprovals: TypedContractMethod<
    [newRequired: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTimelockDuration: TypedContractMethod<
    [newDuration: BigNumberish],
    [void],
    "nonpayable"
  >;

  setWithdrawalLimit: TypedContractMethod<
    [token: AddressLike, limit: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  timelockDuration: TypedContractMethod<[], [bigint], "view">;

  togglePause: TypedContractMethod<[], [void], "nonpayable">;

  totalDeposited: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  totalWithdrawn: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  withdrawalLimits: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  withdrawalRequests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string,
        string
      ] & {
        token: string;
        recipient: string;
        amount: bigint;
        requestTime: bigint;
        executeAfter: bigint;
        approvalCount: bigint;
        executed: boolean;
        cancelled: boolean;
        reason: string;
        kmsSignature: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "APPROVER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "EMERGENCY_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TREASURER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "approveWithdrawal"
  ): TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelWithdrawal"
  ): TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "executeWithdrawal"
  ): TypedContractMethod<
    [requestId: BigNumberish, kmsSignature: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAccountingInfo"
  ): TypedContractMethod<
    [token: AddressLike],
    [
      [bigint, bigint, bigint] & {
        deposited: bigint;
        withdrawn: bigint;
        currentBalance: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTreasuryBalance"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getWithdrawalRequest"
  ): TypedContractMethod<
    [requestId: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string
      ] & {
        token: string;
        recipient: string;
        amount: bigint;
        requestTime: bigint;
        executeAfter: bigint;
        approvalCount: bigint;
        executed: boolean;
        cancelled: boolean;
        reason: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasApproved"
  ): TypedContractMethod<
    [requestId: BigNumberish, approver: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextRequestId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestWithdrawal"
  ): TypedContractMethod<
    [
      token: AddressLike,
      recipient: AddressLike,
      amount: BigNumberish,
      reason: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requiredApprovals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRequiredApprovals"
  ): TypedContractMethod<[newRequired: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTimelockDuration"
  ): TypedContractMethod<[newDuration: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setWithdrawalLimit"
  ): TypedContractMethod<
    [token: AddressLike, limit: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "timelockDuration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "togglePause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalDeposited"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalWithdrawn"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawalLimits"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawalRequests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string,
        string
      ] & {
        token: string;
        recipient: string;
        amount: bigint;
        requestTime: bigint;
        executeAfter: bigint;
        approvalCount: bigint;
        executed: boolean;
        cancelled: boolean;
        reason: string;
        kmsSignature: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyPauseToggled"
  ): TypedContractEvent<
    EmergencyPauseToggledEvent.InputTuple,
    EmergencyPauseToggledEvent.OutputTuple,
    EmergencyPauseToggledEvent.OutputObject
  >;
  getEvent(
    key: "KMSSignatureRecorded"
  ): TypedContractEvent<
    KMSSignatureRecordedEvent.InputTuple,
    KMSSignatureRecordedEvent.OutputTuple,
    KMSSignatureRecordedEvent.OutputObject
  >;
  getEvent(
    key: "RequiredApprovalsUpdated"
  ): TypedContractEvent<
    RequiredApprovalsUpdatedEvent.InputTuple,
    RequiredApprovalsUpdatedEvent.OutputTuple,
    RequiredApprovalsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TimelockDurationUpdated"
  ): TypedContractEvent<
    TimelockDurationUpdatedEvent.InputTuple,
    TimelockDurationUpdatedEvent.OutputTuple,
    TimelockDurationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalApproved"
  ): TypedContractEvent<
    WithdrawalApprovedEvent.InputTuple,
    WithdrawalApprovedEvent.OutputTuple,
    WithdrawalApprovedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalCancelled"
  ): TypedContractEvent<
    WithdrawalCancelledEvent.InputTuple,
    WithdrawalCancelledEvent.OutputTuple,
    WithdrawalCancelledEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalExecuted"
  ): TypedContractEvent<
    WithdrawalExecutedEvent.InputTuple,
    WithdrawalExecutedEvent.OutputTuple,
    WithdrawalExecutedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalLimitUpdated"
  ): TypedContractEvent<
    WithdrawalLimitUpdatedEvent.InputTuple,
    WithdrawalLimitUpdatedEvent.OutputTuple,
    WithdrawalLimitUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalRequested"
  ): TypedContractEvent<
    WithdrawalRequestedEvent.InputTuple,
    WithdrawalRequestedEvent.OutputTuple,
    WithdrawalRequestedEvent.OutputObject
  >;

  filters: {
    "Deposited(address,address,uint256,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "EmergencyPauseToggled(bool)": TypedContractEvent<
      EmergencyPauseToggledEvent.InputTuple,
      EmergencyPauseToggledEvent.OutputTuple,
      EmergencyPauseToggledEvent.OutputObject
    >;
    EmergencyPauseToggled: TypedContractEvent<
      EmergencyPauseToggledEvent.InputTuple,
      EmergencyPauseToggledEvent.OutputTuple,
      EmergencyPauseToggledEvent.OutputObject
    >;

    "KMSSignatureRecorded(uint256,bytes32)": TypedContractEvent<
      KMSSignatureRecordedEvent.InputTuple,
      KMSSignatureRecordedEvent.OutputTuple,
      KMSSignatureRecordedEvent.OutputObject
    >;
    KMSSignatureRecorded: TypedContractEvent<
      KMSSignatureRecordedEvent.InputTuple,
      KMSSignatureRecordedEvent.OutputTuple,
      KMSSignatureRecordedEvent.OutputObject
    >;

    "RequiredApprovalsUpdated(uint256,uint256)": TypedContractEvent<
      RequiredApprovalsUpdatedEvent.InputTuple,
      RequiredApprovalsUpdatedEvent.OutputTuple,
      RequiredApprovalsUpdatedEvent.OutputObject
    >;
    RequiredApprovalsUpdated: TypedContractEvent<
      RequiredApprovalsUpdatedEvent.InputTuple,
      RequiredApprovalsUpdatedEvent.OutputTuple,
      RequiredApprovalsUpdatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "TimelockDurationUpdated(uint256,uint256)": TypedContractEvent<
      TimelockDurationUpdatedEvent.InputTuple,
      TimelockDurationUpdatedEvent.OutputTuple,
      TimelockDurationUpdatedEvent.OutputObject
    >;
    TimelockDurationUpdated: TypedContractEvent<
      TimelockDurationUpdatedEvent.InputTuple,
      TimelockDurationUpdatedEvent.OutputTuple,
      TimelockDurationUpdatedEvent.OutputObject
    >;

    "WithdrawalApproved(uint256,address,uint256)": TypedContractEvent<
      WithdrawalApprovedEvent.InputTuple,
      WithdrawalApprovedEvent.OutputTuple,
      WithdrawalApprovedEvent.OutputObject
    >;
    WithdrawalApproved: TypedContractEvent<
      WithdrawalApprovedEvent.InputTuple,
      WithdrawalApprovedEvent.OutputTuple,
      WithdrawalApprovedEvent.OutputObject
    >;

    "WithdrawalCancelled(uint256,address)": TypedContractEvent<
      WithdrawalCancelledEvent.InputTuple,
      WithdrawalCancelledEvent.OutputTuple,
      WithdrawalCancelledEvent.OutputObject
    >;
    WithdrawalCancelled: TypedContractEvent<
      WithdrawalCancelledEvent.InputTuple,
      WithdrawalCancelledEvent.OutputTuple,
      WithdrawalCancelledEvent.OutputObject
    >;

    "WithdrawalExecuted(uint256,address,address,uint256,bytes32)": TypedContractEvent<
      WithdrawalExecutedEvent.InputTuple,
      WithdrawalExecutedEvent.OutputTuple,
      WithdrawalExecutedEvent.OutputObject
    >;
    WithdrawalExecuted: TypedContractEvent<
      WithdrawalExecutedEvent.InputTuple,
      WithdrawalExecutedEvent.OutputTuple,
      WithdrawalExecutedEvent.OutputObject
    >;

    "WithdrawalLimitUpdated(address,uint256)": TypedContractEvent<
      WithdrawalLimitUpdatedEvent.InputTuple,
      WithdrawalLimitUpdatedEvent.OutputTuple,
      WithdrawalLimitUpdatedEvent.OutputObject
    >;
    WithdrawalLimitUpdated: TypedContractEvent<
      WithdrawalLimitUpdatedEvent.InputTuple,
      WithdrawalLimitUpdatedEvent.OutputTuple,
      WithdrawalLimitUpdatedEvent.OutputObject
    >;

    "WithdrawalRequested(uint256,address,address,uint256,string)": TypedContractEvent<
      WithdrawalRequestedEvent.InputTuple,
      WithdrawalRequestedEvent.OutputTuple,
      WithdrawalRequestedEvent.OutputObject
    >;
    WithdrawalRequested: TypedContractEvent<
      WithdrawalRequestedEvent.InputTuple,
      WithdrawalRequestedEvent.OutputTuple,
      WithdrawalRequestedEvent.OutputObject
    >;
  };
}
