/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IERC3643ComplianceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bindToken"
      | "canTransfer"
      | "created"
      | "destroyed"
      | "isTokenAgent"
      | "isTokenBound"
      | "transferred"
      | "unbindToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "TokenBound" | "TokenUnbound"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "bindToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "canTransfer",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "created",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "destroyed",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isTokenAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTokenBound",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferred",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unbindToken",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "bindToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "canTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "created", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "destroyed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isTokenAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTokenBound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferred",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unbindToken",
    data: BytesLike
  ): Result;
}

export namespace TokenBoundEvent {
  export type InputTuple = [_token: AddressLike];
  export type OutputTuple = [_token: string];
  export interface OutputObject {
    _token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenUnboundEvent {
  export type InputTuple = [_token: AddressLike];
  export type OutputTuple = [_token: string];
  export interface OutputObject {
    _token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IERC3643Compliance extends BaseContract {
  connect(runner?: ContractRunner | null): IERC3643Compliance;
  waitForDeployment(): Promise<this>;

  interface: IERC3643ComplianceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bindToken: TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;

  canTransfer: TypedContractMethod<
    [_from: AddressLike, _to: AddressLike, _amount: BigNumberish],
    [boolean],
    "view"
  >;

  created: TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  destroyed: TypedContractMethod<
    [_from: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  isTokenAgent: TypedContractMethod<
    [_agentAddress: AddressLike],
    [boolean],
    "view"
  >;

  isTokenBound: TypedContractMethod<[_token: AddressLike], [boolean], "view">;

  transferred: TypedContractMethod<
    [_from: AddressLike, _to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  unbindToken: TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bindToken"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "canTransfer"
  ): TypedContractMethod<
    [_from: AddressLike, _to: AddressLike, _amount: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "created"
  ): TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "destroyed"
  ): TypedContractMethod<
    [_from: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isTokenAgent"
  ): TypedContractMethod<[_agentAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isTokenBound"
  ): TypedContractMethod<[_token: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferred"
  ): TypedContractMethod<
    [_from: AddressLike, _to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unbindToken"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "TokenBound"
  ): TypedContractEvent<
    TokenBoundEvent.InputTuple,
    TokenBoundEvent.OutputTuple,
    TokenBoundEvent.OutputObject
  >;
  getEvent(
    key: "TokenUnbound"
  ): TypedContractEvent<
    TokenUnboundEvent.InputTuple,
    TokenUnboundEvent.OutputTuple,
    TokenUnboundEvent.OutputObject
  >;

  filters: {
    "TokenBound(address)": TypedContractEvent<
      TokenBoundEvent.InputTuple,
      TokenBoundEvent.OutputTuple,
      TokenBoundEvent.OutputObject
    >;
    TokenBound: TypedContractEvent<
      TokenBoundEvent.InputTuple,
      TokenBoundEvent.OutputTuple,
      TokenBoundEvent.OutputObject
    >;

    "TokenUnbound(address)": TypedContractEvent<
      TokenUnboundEvent.InputTuple,
      TokenUnboundEvent.OutputTuple,
      TokenUnboundEvent.OutputObject
    >;
    TokenUnbound: TypedContractEvent<
      TokenUnboundEvent.InputTuple,
      TokenUnboundEvent.OutputTuple,
      TokenUnboundEvent.OutputObject
    >;
  };
}
