/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC3643IdentityRegistry,
  IERC3643IdentityRegistryInterface,
} from "../../contracts/IERC3643IdentityRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_userAddress",
        type: "address",
      },
    ],
    name: "contains",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_userAddress",
        type: "address",
      },
    ],
    name: "identity",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_userAddress",
        type: "address",
      },
    ],
    name: "investorCountry",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_userAddress",
        type: "address",
      },
    ],
    name: "isVerified",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IERC3643IdentityRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IERC3643IdentityRegistryInterface {
    return new Interface(_abi) as IERC3643IdentityRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC3643IdentityRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IERC3643IdentityRegistry;
  }
}
